DROP TABLE IF EXISTS TBL_ORDER;

CREATE TABLE TBL_ORDER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  order_by VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);