DROP TABLE IF EXISTS TBL_PAYMENT;

CREATE TABLE TBL_ORDER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  amount INT NOT NULL,
  payment_type VARCHAR(250) NOT NULL,
  status VARCHAR(250) DEFAULT NULL,
  order_id INT NOT NULL default 0
);